### ISSUE TITLE
NullReferenceException in OnLoad at window.Flyout.Items

### ISSUE THREAD

**Issue by sebastientromp** [andburn/hdt-plugin-statsconverter#16]
Hey andburn,

I tried to compile and run the plugin from sources, but got an exception when calling the OnLoad() method:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at HDT.Plugins.StatsConverter.StatsConverterPlugin.SetSettingsFlyout() in G:\Source\HDT plugins\hdt-plugin-statsconverter\StatsConverter\StatsConverterPlugin.cs:line 85
   at HDT.Plugins.StatsConverter.StatsConverterPlugin.<OnLoad>d__14.MoveNext() in G:\Source\HDT plugins\hdt-plugin-statsconverter\StatsConverter\StatsConverterPlugin.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Apparently the Hearthstone_Deck_Tracker.API.Core.MainWindow.Flyouts is null

```
    private static void SetSettingsFlyout()
    {
        var window = Hearthstone_Deck_Tracker.API.Core.MainWindow;
        var flyouts = window.Flyouts.Items;
```

Any idea of how to solve this?

**Comment by andburn** [comment]
Not sure off hand, but I'll have a look into it today

**Comment by sebastientromp** [comment]
Thanks! I'm still 100% newbie to C# and windows app development, so maybe I just messed things up when compiling or setting up my environment.

**Comment by andburn** [comment]
I've tried this out a few different ways, seems to be working fine for me. I can't think why it would be happening. Thought maybe something to do with the _MahApps_ version (HDT uses v1.1.2), but it shouldn't even load the plugin then. 

@azeier do you have any thoughts on this?

**Comment by sebastientromp** [comment]
Just updated my MahApps version to 1.1.2, and seems to work (at least the window.Flyouts isn't `null` anymore). Thanks!

**Comment by andburn** [comment]
Great
